---
- name: Set the timezone
  timezone:
    name: Australia/Darwin

- name: Configure automatic ssh 
  block:
    - name: Create skel .ssh dir
      file:
        state: directory
        path: /etc/skel/.ssh
    - name: Copy ssh config to skel
      copy:
        src: files/ssh/authorized_keys
        dest: /etc/skel/.ssh

- name: Install simple software without any additional configuration
  community.general.rpm_ostree_pkg:
    name: 
      - podman-compose
      - htop
      - tldr
      - g++
    state: present
  notify:
  - Reboot if required

- name: Install and configure zsh shell
  block:
    - name: Install zsh
      community.general.rpm_ostree_pkg:
        name: zsh
        state: present
      notify:
      - Reboot if required
    - name: Make ohmyzsh git directory safe
      command: git config --global --add safe.directory /etc/skel/.oh-my-zsh
      check_mode: no
    - name: Clone ohmyzsh repo
      git:
        repo: "https://github.com/ohmyzsh/ohmyzsh.git"
        dest: /etc/skel/.oh-my-zsh
    - name: Copy zsh config to skel dir
      copy:
        src: files/zshrc/.zshrc
        dest: /etc/skel
    - name: Copy bash_profile to skel dir
      copy:
        src: files/zshrc/.bash_profile
        dest: /etc/skel
  when: INSTALL_ZSH

- name: Install and configure tmux
  block:
    - name: Install tmux
      community.general.rpm_ostree_pkg:
        name: tmux
        state: present
    - name: Make tmux git directory safe
      command: git config --global --add safe.directory /etc/skel/.tmux
      check_mode: no
    - name: Download pretty tmux from git
      git:
        repo: "https://github.com/gpakosz/.tmux.git"
        dest: /etc/skel/.tmux
    - name: Copy local tmux config to home dir
      command: cp .tmux/.tmux.conf.local .
      args:
        chdir: /etc/skel
    - name: Create tmux config symlink
      command: ln -s -f .tmux/.tmux.conf
      args:
        chdir: /etc/skel
  when: INSTALL_TMUX

- name: Install and configure nvim
  block:
    - name: Install nvim and ripgrep
      community.general.rpm_ostree_pkg:
        name: 
          - neovim
          - ripgrep
        state: present
    - name: Create .config dir in skel
      file:
        path: /etc/skel/.config
        state: directory
    - name: Make nvim git directory safe
      command: git config --global --add safe.directory /etc/skel/.config/nvim
      check_mode: no
    - name: Download nvchad from git
      git:
        repo: https://github.com/nvchad/nvchad
        depth: 1
        dest: /etc/skel/.config/nvim
    - name: Create fonts directory 
      file:
        path: /etc/skel/.local/share/fonts
        state: directory
#    - name: Download font 
#      unarchive:
#        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.1/Terminus.zip
#        dest: /etc/skel/.local/share/fonts
#        remote_src: true
  when: INSTALL_VIM

- name: Configure MOTD
  block:
    - name: Install neofetch
      community.general.rpm_ostree_pkg:
        name: neofetch
        state: present
    - name: Ensure .config file exists
      file:
        path: /etc/skel/.config/neofetch
        state: directory
    - name: Copy neofetch config
      copy:
        src: files/neofetch/config.conf
        dest: /etc/skel/.config/neofetch/
    - name: Copy megacorplogo
      copy:
        src: files/neofetch/megacorplogo
        dest: /etc/skel/.config/neofetch/
