- name: install nfs-utils
  community.general.rpm_ostree_pkg: 
    name: nfs-utils

- name: Create a mountable directory if it does not exist
  file:
    path: /opt/nfs
    state: directory
    mode: '0775'

- name: enable rpcbind nfslock nfs
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - rpcbind
    - nfslock
    - nfs

- name: Copy exports file.
  template:
    src: ./ansible/exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644

- name: NFS apply change configrue
  shell: systemctl reload nfs;exportfs -a
